#  Server configuration
server:
  port: 8080
  servlet:
    context-path: /payment-platform/v1


# Spring configuration
spring:
  application:
    name: payment-platform
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  cache:
    caffeine:
      spec: maximumSize=100, expireAfterWrite=1m


# External APIs Configuration
external-apis:
  fraud-api:
    url: http://demo8471017.mockable.io/fraud-ok

  bank-api:
    url: https://demo8471017.mockable.io/bank-ok

# failed scenarios
#  fraud-api:
#    url: https://demo8471017.mockable.io/fraud-failed
#  bank-api:
#    url: https://demo8471017.mockable.io/bank-failed


# Logger Configuration
logging:
  level:
    com:
      payu:
        payment_platform: INFO


# Health Configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    db:
      enabled: false
  #  endpoint:
  #    health:
  #      show-details: always
  info:
    git:
      mode: full